config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' 

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'  
  get  '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'projects/home' => 'projects#home'

  resources :projects
  resources :vehicles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def home
    @projects = Project.all
    @vehicles = Vehicle.all
  end
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:product, :name, :code, :number, :plant, :volume, :ratio, :life, :sop, :eop, :project_manger, :vehicle_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :plant %>
    <%= form.text_field :plant %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.text_field :volume %>
  </div>

  <div class="field">
    <%= form.label :ratio %>
    <%= form.text_field :ratio %>
  </div>

  <div class="field">
    <%= form.label :life %>
    <%= form.text_field :life %>
  </div>

  <div class="field">
    <%= form.label :sop %>
    <%= form.text_field :sop %>
  </div>

  <div class="field">
    <%= form.label :eop %>
    <%= form.text_field :eop %>
  </div>

  <div class="field">
    <%= form.label :project_manger %>
    <%= form.text_field :project_manger %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select(:vehidle_id, Vehicle.all, :id,:name,include_blank: '選択してください') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table border = 2 width = 70%>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.name %></td>
        <td><%= image_tag vehicle.image.url, size: '60x40' %></td> 
       
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table border = 2 width = 90%>
  <thead>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th>Code</th>
      <th>Number</th>
      <th>Plant</th>
      <th>Volume</th>
      <th>Ratio</th>
      <th>Life</th>
      <th>Sop</th>
      <th>Eop</th>
      <th>Project manger</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.product %></td>
        <td><%= project.name %></td>
        <td><%= project.code %></td>
        <td><%= project.number %></td>
        <td><%= project.plant %></td>
        <td><%= project.volume %></td>
        <td><%= project.ratio %></td>
        <td><%= project.life %></td>
        <td><%= project.sop %></td>
        <td><%= project.eop %></td>
        <td><%= project.project_manger %></td>
        <td><%= project.vehicle_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>


<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table border = 2 width = 85%>
  <thead>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th>Code</th>
      <th>Number</th>
      <th>Plant</th>
      <th>Volume</th>
      <th>Ratio</th>
      <th>Life</th>
      <th>Sop</th>
      <th>Eop</th>
      <th>Project manger</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.product %></td>
        <td><%= project.name %></td>
        <td><%= project.code %></td>
        <td><%= project.number %></td>
        <td><%= project.plant %></td>
        <td><%= project.volume %></td>
        <td><%= project.ratio %></td>
        <td><%= project.life %></td>
        <td><%= project.sop %></td>
        <td><%= project.eop %></td>
        <td><%= project.project_manger %></td>
        <td><%= project.vehicle_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @project.product %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Number:</strong>
  <%= @project.number %>
</p>

<p>
  <strong>Plant:</strong>
  <%= @project.plant %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @project.volume %>
</p>

<p>
  <strong>Ratio:</strong>
  <%= @project.ratio %>
</p>

<p>
  <strong>Life:</strong>
  <%= @project.life %>
</p>

<p>
  <strong>Sop:</strong>
  <%= @project.sop %>
</p>

<p>
  <strong>Eop:</strong>
  <%= @project.eop %>
</p>

<p>
  <strong>Project manger:</strong>
  <%= @project.project_manger %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @project.vehicle_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>